### ISSUE TITLE
Static site generator?

### ISSUE THREAD

**Issue by willklein** [Denver-Devs/denver-devs.github.io#8]
I'm interested in contributing, and the first thing I noticed is the site is currently a single HTML file. I'm experienced with using static site generators like Jekyll and Wintersmith. Would it be valuable for me to set one up and submit a PR?

The biggest benefit is that it becomes easier to maintain the site. If you want to add an event, resource, or other content, you just create a new Markdown or YAML file in the appropriate directory.

The downside is that you require a build step for previewing changes on your local machine. Ruby or JavaScript-based tooling is trivial though. Dependencies and tasks can be rolled into the repo too.

Let me know what you think.

**Comment by talon** [comment]
I am in support of a static site generator. Jekyll works the best with github and would likely be my preferred choice. I agree that a nice directory structure of markdown files would be great because markdown is a pleasing format for a more general audience and with proper documentation about how to contribute would theoretically make that process significantly easier.

**Comment by DrewDahlman** [comment]
:+1:

**Comment by danhannigan** [comment]
On first setting it up I had gone with a single HTML file instead of Jekyll simply to cut out what I saw as extra complexity (because to me a page that is ultimately a single static html page shouldn't really need a build process/directories/etc) - also because I had the idea that I'd be the only one updating the page, but as I've seen others are more than happy to contribute and update. 

I'm familiar with Jekyll though, not Wintersmith (something I'm sure I could learn) - I had also considered using Assemble (http://assemble.io/)

If Jekyll is what the group wants then hey - I'm easy, I can work with that.

**Comment by willklein** [comment]
Awesome. I also think Jekyll would work best for a community-oriented effort, and especially with GitHub Pages. I can whip up a Jekyll PR this weekend.

**Comment by chadperson** [comment]
Hi! I tossed some notes in the Denver Devs slack group on this - but we are a new startup in Denver that ships privately hosted jekyll sites with user auth, policy management, and payments. If you want to host on us, I’ll comp the fee for the group. We’d love to have this community site on BowTie, and are happy to donate the space. As we continue to build and shape features, the feedback from this group would be amazing.

**Comment by willklein** [comment]
Discussion continued here: https://denver-devs.slack.com/archives/general/p1435856943005340
